name: 'Component Library Deployment'

on: push

jobs:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v1
    - run: yarn
    - uses: chromaui/action@v1
      with:
        projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
        token: ${{ secrets.GH_TOKEN }}